nsys profile --trace=cuda,nvtx --output=results/host_to_device_ce_ce --force-overwrite true ./nvbandwidth -t host_to_device_ce_ce --cooldown 8  -v > results/host_to_device_ce_ce.txt
nsys profile --trace=cuda,nvtx --output=results/host_to_device_ce_sm --force-overwrite true ./nvbandwidth -t host_to_device_ce_sm --cooldown 12 -v > results/host_to_device_ce_sm.txt
nsys profile --trace=cuda,nvtx --output=results/host_to_device_sm_ce --force-overwrite true ./nvbandwidth -t host_to_device_sm_ce --cooldown 12 -v > results/host_to_device_sm_ce.txt
nsys profile --trace=cuda,nvtx --output=results/host_to_device_sm_sm --force-overwrite true ./nvbandwidth -t host_to_device_sm_sm --cooldown 12 -v > results/host_to_device_sm_sm.txt
nsys profile --trace=cuda,nvtx --output=results/device_to_host_ce_ce --force-overwrite true ./nvbandwidth -t device_to_host_ce_ce --cooldown 8  -v > results/device_to_host_ce_ce.txt
nsys profile --trace=cuda,nvtx --output=results/device_to_host_ce_sm --force-overwrite true ./nvbandwidth -t device_to_host_ce_sm --cooldown 12 -v > results/device_to_host_ce_sm.txt
nsys profile --trace=cuda,nvtx --output=results/device_to_host_sm_ce --force-overwrite true ./nvbandwidth -t device_to_host_sm_ce --cooldown 8  -v > results/device_to_host_sm_ce.txt
nsys profile --trace=cuda,nvtx --output=results/device_to_host_sm_sm --force-overwrite true ./nvbandwidth -t device_to_host_sm_sm --cooldown 12 -v > results/device_to_host_sm_sm.txt

nsys profile --trace=cuda,nvtx --output=results/device_to_device_read_ce_ce  --force-overwrite true ./nvbandwidth -t device_to_device_read_ce_ce  --cooldown 24 -v > results/device_to_device_read_ce_ce.txt
nsys profile --trace=cuda,nvtx --output=results/device_to_device_read_ce_sm  --force-overwrite true ./nvbandwidth -t device_to_device_read_ce_sm  --cooldown 24 -v > results/device_to_device_read_ce_sm.txt
nsys profile --trace=cuda,nvtx --output=results/device_to_device_read_sm_ce  --force-overwrite true ./nvbandwidth -t device_to_device_read_sm_ce  --cooldown 24 -v > results/device_to_device_read_sm_ce.txt
nsys profile --trace=cuda,nvtx --output=results/device_to_device_read_sm_sm  --force-overwrite true ./nvbandwidth -t device_to_device_read_sm_sm  --cooldown 12 -v > results/device_to_device_read_sm_sm.txt
nsys profile --trace=cuda,nvtx --output=results/device_to_device_write_ce_ce --force-overwrite true ./nvbandwidth -t device_to_device_write_ce_ce --cooldown 8  -v > results/device_to_device_write_ce_ce.txt
nsys profile --trace=cuda,nvtx --output=results/device_to_device_write_ce_sm --force-overwrite true ./nvbandwidth -t device_to_device_write_ce_sm --cooldown 12 -v > results/device_to_device_write_ce_sm.txt
nsys profile --trace=cuda,nvtx --output=results/device_to_device_write_sm_ce --force-overwrite true ./nvbandwidth -t device_to_device_write_sm_ce --cooldown 12 -v > results/device_to_device_write_sm_ce.txt
nsys profile --trace=cuda,nvtx --output=results/device_to_device_write_sm_sm --force-overwrite true ./nvbandwidth -t device_to_device_write_sm_sm --cooldown 12 -v > results/device_to_device_write_sm_sm.txt

nsys profile --trace=cuda,nvtx --output=results/device_to_host_ce_device_to_device_read_ce  --force-overwrite true ./nvbandwidth -t device_to_host_ce_device_to_device_read_ce  --cooldown 24 -v > results/device_to_host_ce_device_to_device_read_ce.txt
nsys profile --trace=cuda,nvtx --output=results/device_to_host_ce_device_to_device_read_sm  --force-overwrite true ./nvbandwidth -t device_to_host_ce_device_to_device_read_sm  --cooldown 24 -v > results/device_to_host_ce_device_to_device_read_sm.txt
nsys profile --trace=cuda,nvtx --output=results/device_to_host_sm_device_to_device_read_ce  --force-overwrite true ./nvbandwidth -t device_to_host_sm_device_to_device_read_ce  --cooldown 24 -v > results/device_to_host_sm_device_to_device_read_ce.txt
nsys profile --trace=cuda,nvtx --output=results/device_to_host_sm_device_to_device_read_sm  --force-overwrite true ./nvbandwidth -t device_to_host_sm_device_to_device_read_sm  --cooldown 24 -v > results/device_to_host_sm_device_to_device_read_sm.txt
nsys profile --trace=cuda,nvtx --output=results/device_to_host_ce_device_to_device_write_ce --force-overwrite true ./nvbandwidth -t device_to_host_ce_device_to_device_write_ce --cooldown 24 -v > results/device_to_host_ce_device_to_device_write_ce.txt
nsys profile --trace=cuda,nvtx --output=results/device_to_host_ce_device_to_device_write_sm --force-overwrite true ./nvbandwidth -t device_to_host_ce_device_to_device_write_sm --cooldown 24 -v > results/device_to_host_ce_device_to_device_write_sm.txt
nsys profile --trace=cuda,nvtx --output=results/device_to_host_sm_device_to_device_write_ce --force-overwrite true ./nvbandwidth -t device_to_host_sm_device_to_device_write_ce --cooldown 24 -v > results/device_to_host_sm_device_to_device_write_ce.txt
nsys profile --trace=cuda,nvtx --output=results/device_to_host_sm_device_to_device_write_sm --force-overwrite true ./nvbandwidth -t device_to_host_sm_device_to_device_write_sm --cooldown 24 -v > results/device_to_host_sm_device_to_device_write_sm.txt

nsys profile --trace=cuda,nvtx --output=results/host_to_device_ce_device_to_device_read_ce  --force-overwrite true ./nvbandwidth -t host_to_device_ce_device_to_device_read_ce  --cooldown 24 -v > results/host_to_device_ce_device_to_device_read_ce.txt
nsys profile --trace=cuda,nvtx --output=results/host_to_device_ce_device_to_device_read_sm  --force-overwrite true ./nvbandwidth -t host_to_device_ce_device_to_device_read_sm  --cooldown 24 -v > results/host_to_device_ce_device_to_device_read_sm.txt
nsys profile --trace=cuda,nvtx --output=results/host_to_device_sm_device_to_device_read_ce  --force-overwrite true ./nvbandwidth -t host_to_device_sm_device_to_device_read_ce  --cooldown 24 -v > results/host_to_device_sm_device_to_device_read_ce.txt
nsys profile --trace=cuda,nvtx --output=results/host_to_device_sm_device_to_device_read_sm  --force-overwrite true ./nvbandwidth -t host_to_device_sm_device_to_device_read_sm  --cooldown 24 -v > results/host_to_device_sm_device_to_device_read_sm.txt
nsys profile --trace=cuda,nvtx --output=results/host_to_device_ce_device_to_device_write_ce --force-overwrite true ./nvbandwidth -t host_to_device_ce_device_to_device_write_ce --cooldown 24 -v > results/host_to_device_ce_device_to_device_write_ce.txt
nsys profile --trace=cuda,nvtx --output=results/host_to_device_ce_device_to_device_write_sm --force-overwrite true ./nvbandwidth -t host_to_device_ce_device_to_device_write_sm --cooldown 24 -v > results/host_to_device_ce_device_to_device_write_sm.txt
nsys profile --trace=cuda,nvtx --output=results/host_to_device_sm_device_to_device_write_ce --force-overwrite true ./nvbandwidth -t host_to_device_sm_device_to_device_write_ce --cooldown 24 -v > results/host_to_device_sm_device_to_device_write_ce.txt
nsys profile --trace=cuda,nvtx --output=results/host_to_device_sm_device_to_device_write_sm --force-overwrite true ./nvbandwidth -t host_to_device_sm_device_to_device_write_sm --cooldown 24 -v > results/host_to_device_sm_device_to_device_write_sm.txt